Add "Security" workflow (#111)
## Changelog

- Update license copyright year to 2024

---

Powered by
[FantasticFiasco/action-update-license-year](https://github.com/FantasticFiasco/action-update-license-year)

---------

Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: fabasoad <fabasoad@gmail.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,23 +14,24 @@ runs:
   using: "composite"
   steps:
     - name: Fail
-      uses: actions/github-script@v7
       if: ${{ runner.os == 'Windows' }}
-      with:
-        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
+      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      shell: sh
     - name: Collect info
       if: ${{ runner.os != 'Windows' }}
       id: info
+      env:
+        INPUT_VERSION: "${{ inputs.version }}"
       run: |
-        echo "MINT_INSTALLED=$(if command -v mint >/dev/null 2>&1; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
+        echo "MINT_INSTALLED=$(if command -v mint >/dev/null 2>&1; then echo true; else echo false; fi)" >> "$GITHUB_OUTPUT"
         mkdir -p "$GITHUB_WORKSPACE/mint"
-        echo "MINT_PATH=$GITHUB_WORKSPACE/mint" >> $GITHUB_OUTPUT
-        if [ "${{ runner.os }}" = "Linux" ]; then
-          MINT_BINARY=mint-${{ inputs.version }}-linux
+        echo "MINT_PATH=$GITHUB_WORKSPACE/mint" >> "$GITHUB_OUTPUT"
+        if [ "${RUNNER_OS}" = "Linux" ]; then
+          MINT_BINARY=mint-${INPUT_VERSION}-linux
         else
-          MINT_BINARY=mint-${{ inputs.version }}-osx
+          MINT_BINARY=mint-${INPUT_VERSION}-osx
         fi
-        echo "MINT_BINARY=$MINT_BINARY" >> $GITHUB_OUTPUT
+        echo "MINT_BINARY=$MINT_BINARY" >> "$GITHUB_OUTPUT"
       shell: sh
     - name: Download
       if: ${{ runner.os != 'Windows' && steps.info.outputs.MINT_INSTALLED == 'false' }}
@@ -46,8 +47,8 @@ runs:
     - name: Install
       if: ${{ runner.os != 'Windows' && steps.info.outputs.MINT_INSTALLED == 'false' }}
       run: |
-        mv ${{ steps.info.outputs.MINT_BINARY }} mint
+        mv "${{ steps.info.outputs.MINT_BINARY }}" mint
         chmod +x mint
-        echo "${{ steps.info.outputs.MINT_PATH }}" >> $GITHUB_PATH
+        echo "${{ steps.info.outputs.MINT_PATH }}" >> "$GITHUB_PATH"
       shell: sh
       working-directory: ${{ steps.info.outputs.MINT_PATH }}
