Test new approach

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,9 +7,29 @@ branding:
   color: green
 inputs:
   version:
-    description: 'Mint version.'
+    description: 'Mint version'
     required: false
     default: 0.16.1
 runs:
-  using: 'node16'
-  main: 'dist/index.js'
+  using: 'composite'
+  steps:
+    - name: Collect info
+      id: info
+      run: |
+        if [[ "${{ runner.os }}" == "macOS" ]]; then
+          MINT_BINARY=mint-${{ inputs.version }}-osx
+        elif [[ "${{ runner.os }}" == "Linux" ]]; then
+          MINT_BINARY=mint-${{ inputs.version }}-linux
+        else
+          echo "::error::Windows is not supported"
+          exit 1
+        fi
+        echo "MINT_BINARY=$MINT_BINARY" >> $GITHUB_OUTPUT
+      shell: bash
+    - name: Install
+      if: ${{ runner.os != 'Windows' }}
+      run: |
+        curl https://github.com/mint-lang/mint/releases/download/${{ inputs.version }}/${{ steps.info.outputs.MINT_BINARY }} -o mint
+        chmod +x mint
+        echo "${{ github.action_path }}" >> $GITHUB_PATH
+      shell: bash
