Bump hook

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,10 +15,11 @@ runs:
   steps:
     - name: Fail
       if: ${{ runner.os == 'Windows' }}
-      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      run: |
+        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
       shell: sh
     - name: Collect info
-      if: ${{ runner.os != 'Windows' }}
       id: info
       env:
         INPUT_VERSION: "${{ inputs.version }}"
@@ -34,7 +35,7 @@ runs:
         echo "MINT_BINARY=$MINT_BINARY" >> "$GITHUB_OUTPUT"
       shell: sh
     - name: Download
-      if: ${{ runner.os != 'Windows' && steps.info.outputs.MINT_INSTALLED == 'false' }}
+      if: ${{ steps.info.outputs.MINT_INSTALLED == 'false' }}
       uses: robinraju/release-downloader@v1.10
       with:
         repository: mint-lang/mint
@@ -45,7 +46,7 @@ runs:
         zipBall: false
         out-file-path: mint
     - name: Install
-      if: ${{ runner.os != 'Windows' && steps.info.outputs.MINT_INSTALLED == 'false' }}
+      if: ${{ steps.info.outputs.MINT_INSTALLED == 'false' }}
       run: |
         mv "${{ steps.info.outputs.MINT_BINARY }}" mint
         chmod +x mint
