Bump actionlint from 1.7.4 to 1.7.6 (#120)
## Changelog

- Update license copyright year to 2025

---

Powered by
[FantasticFiasco/action-update-license-year](https://github.com/FantasticFiasco/action-update-license-year)

---------

Co-authored-by: github-actions <github-actions@github.com>
Co-authored-by: fabasoad <fabasoad@gmail.com>

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -1,37 +1,58 @@
 ---
 name: Functional Tests
 
-on:
-  pull_request: {}
+on: # yamllint disable-line rule:truthy
   push:
     branches:
       - main
+  pull_request:
+    paths:
+      - .github/workflows/functional-tests.yml
+      - src/**
+      - action.yml
+  schedule:
+    # Every Friday at 09:00 JST
+    - cron: "0 0 * * 5"
+  workflow_dispatch: {}
 
 defaults:
   run:
     shell: sh
 
 jobs:
-  functional-tests:
-    name: Run init
+  get-versions:
+    name: Get 3 latest versions
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    outputs:
+      versions: ${{ steps.prepare-list.outputs.versions }}
+    steps:
+      - name: Get releases
+        id: github-releases
+        uses: yakubique/github-releases@v1.2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          repository: "mint-lang/mint"
+          sort: "desc"
+      - name: Prepare list
+        id: prepare-list
+        env:
+          RELEASES_AMOUNT: "3"
+        run: |
+          versions=$(echo '${{ steps.github-releases.outputs.releases }}' \
+            | jq -c -r --arg n "${RELEASES_AMOUNT}" '.[0:($n | tonumber)] | . += ["latest"]')
+          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
+  setup-mint:
+    name: Setup mint
+    needs: [get-versions]
+    runs-on: ${{ matrix.os }}-latest
     timeout-minutes: 5
     strategy:
       fail-fast: false
       matrix:
-        os: ["ubuntu-latest", "macos-13", "macos-latest"]
-        version: ["0.21.0", "0.20.1", "0.20.0", "0.19.0", "0.18.0"]
-        exclude:
-          - os: "macos-latest"
-            version: "0.18.0"
-          - os: "macos-latest"
-            version: "0.19.0"
-          - os: "macos-13"
-            version: "0.20.0"
-          - os: "macos-13"
-            version: "0.20.1"
-          - os: "macos-13"
-            version: "0.21.0"
-    runs-on: ${{ matrix.os }}
+        os: ["ubuntu", "macos"]
+        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
@@ -41,3 +62,36 @@ jobs:
           version: ${{ matrix.version }}
       - name: Print version
         run: mint version
+  test-force:
+    name: Test force
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup Mint 1
+        id: setup-mint-1
+        uses: ./
+      - name: Setup Mint 2
+        id: setup-mint-2
+        uses: ./
+        with:
+          force: ${{ matrix.force }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-mint-1" \
+            "${{ steps.setup-mint-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-mint-2" \
+            "${{ steps.setup-mint-2.outputs.installed }}" \
+            "${{ matrix.force }}"
